import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen justify-between items-center`}>
        <header>
          <h2 className="text-2xl m-10">Quiz generator!</h2>
        </header>
        {children}
        <footer>Created by Marcos Braga Choma - 2024</footer>
      </body>
    </html>
  );
}
